//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: self-portrait (cli)
//! AC description: When the file does not exist in the current HEAD but did historically (e.g. it was deleted), the extractor still walks the history — exits 0 with all commits in `commits` and a top-level `"deleted_at": "<RFC3339>"` field. If the file never existed under any name, exits with code 3 and stderr containing the path and `no commits found`.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac4() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC4 not yet implemented — see file header");
}
