//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: self-portrait (cli)
//! AC description: Commits that touched the file with a trivial change (no semantic diff after the rename) still appear and their `diff` is included verbatim; the consumer decides whether to collapse them. The extractor does not editorialize.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac3() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC3 not yet implemented — see file header");
}
